spring:
  security:
    oauth2:
      client:
        registration:
          pipedrive:
            client-id: 1ac90dc9db1424af
            client-secret: 0fdc47b869f38ae0128604c23d9e6363c8bb4fc1
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/authorize/oauth2/code/pipedrive
        provider:
          pipedrive:
            authorization-uri: https://oauth.pipedrive.com/oauth/authorize
            token-uri: https://oauth.pipedrive.com/oauth/token
